title: octotrike.org
author: trikers
logo: images/octotrike_logo.png
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  talks:
    output: true
plugins:
  - jekyll-seo-tag
