name: Preview Website
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Jekyll Build
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
      - name: Upload to Pages
        run: |
          git clone "https://${{ secrets.GH_PAT }}@github.com/LiptonB/trike-preview" && cd trike-preview && date > the-date && git add the-date && git commit -m "testing" && git push
